-- Expert Planner: Fase 1. Voer dit bestand uit in Supabase SQL Editor of via de Supabase CLI.
create extension if not exists "pgcrypto";
create type public.app_role as enum ('administrator', 'planner', 'expert');
create type public.customer_status as enum ('new', 'active', 'planned', 'completed', 'invalid_address', 'archived');

create table public.users (id uuid primary key references auth.users(id) on delete cascade, full_name text not null default '', role public.app_role not null default 'expert', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.experts (id uuid primary key default gen_random_uuid(), user_id uuid unique references public.users(id) on delete set null, name text not null, start_address jsonb not null default '{}'::jsonb, end_address jsonb not null default '{}'::jsonb, work_days smallint[] not null default '{1,2,3,4,5}', start_time time not null default '08:00', end_time time not null default '17:00', break_minutes integer not null default 30 check (break_minutes >= 0), default_visit_minutes integer not null default 30 check (default_visit_minutes > 0), service_areas text[] not null default '{}', excluded_areas text[] not null default '{}', preferences jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.customers (id uuid primary key default gen_random_uuid(), customer_number text unique, name text not null, address_line text not null, postal_code text, city text, country_code char(2) not null default 'NL', phone text, email text, priority smallint not null default 3 check (priority between 1 and 5), desired_visit_minutes integer, notes text, available_days smallint[] not null default '{}', available_windows jsonb not null default '[]'::jsonb, status public.customer_status not null default 'new', assigned_expert_id uuid references public.experts(id) on delete set null, latitude numeric(9,6), longitude numeric(9,6), geocode_status text not null default 'pending', extra_fields jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.availability (id uuid primary key default gen_random_uuid(), customer_id uuid references public.customers(id) on delete cascade, expert_id uuid references public.experts(id) on delete cascade, starts_at timestamptz not null, ends_at timestamptz not null, kind text not null, check (num_nonnulls(customer_id, expert_id) = 1), check (ends_at > starts_at));
create table public.routes (id uuid primary key default gen_random_uuid(), expert_id uuid not null references public.experts(id), route_date date not null, status text not null default 'draft', total_travel_seconds integer, total_distance_meters integer, score numeric, engine text, engine_result jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(expert_id, route_date));
create table public.appointments (id uuid primary key default gen_random_uuid(), customer_id uuid not null references public.customers(id), expert_id uuid not null references public.experts(id), route_id uuid references public.routes(id) on delete set null, starts_at timestamptz not null, ends_at timestamptz not null, selection_rank smallint check (selection_rank between 1 and 3), status text not null default 'proposed', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check (ends_at > starts_at));
create table public.route_stops (id uuid primary key default gen_random_uuid(), route_id uuid not null references public.routes(id) on delete cascade, appointment_id uuid references public.appointments(id) on delete set null, stop_order integer not null check (stop_order > 0), planned_arrival timestamptz, planned_departure timestamptz, travel_seconds integer, distance_meters integer, stop_type text not null default 'customer', notes text, unique(route_id, stop_order));
create table public.settings (id uuid primary key default gen_random_uuid(), scope text not null default 'organization', expert_id uuid references public.experts(id) on delete cascade, key text not null, value jsonb not null, updated_at timestamptz not null default now(), unique nulls not distinct(scope, expert_id, key));
create table public.import_history (id uuid primary key default gen_random_uuid(), uploaded_by uuid references public.users(id) on delete set null, source_filename text not null, source_type text not null, column_mapping jsonb not null default '{}'::jsonb, row_count integer not null default 0, imported_count integer not null default 0, rejected_count integer not null default 0, validation_summary jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());

-- Een profiel wordt automatisch aangemaakt zodra Supabase een account registreert.
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.users (id, full_name) values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', ''));
  return new;
end;
$$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

alter table public.users enable row level security; alter table public.experts enable row level security; alter table public.customers enable row level security; alter table public.availability enable row level security; alter table public.routes enable row level security; alter table public.appointments enable row level security; alter table public.route_stops enable row level security; alter table public.settings enable row level security; alter table public.import_history enable row level security;
create or replace function public.current_role() returns public.app_role language sql stable security definer set search_path = public as $$ select role from public.users where id = auth.uid() $$;
create policy "authenticated users can read operational data" on public.experts for select to authenticated using (true);
create policy "staff or assigned expert reads customers" on public.customers for select to authenticated using (public.current_role() in ('administrator','planner') or assigned_expert_id in (select id from public.experts where user_id = auth.uid()));
create policy "admins and planners manage experts" on public.experts for all to authenticated using (public.current_role() in ('administrator','planner')) with check (public.current_role() in ('administrator','planner'));
create policy "admins and planners manage customers" on public.customers for all to authenticated using (public.current_role() in ('administrator','planner')) with check (public.current_role() in ('administrator','planner'));
create policy "users read own profile" on public.users for select to authenticated using (id = auth.uid());
create policy "admins manage profiles" on public.users for all to authenticated using (public.current_role() = 'administrator') with check (public.current_role() = 'administrator');
create policy "operational access" on public.availability for all to authenticated using (public.current_role() in ('administrator','planner')) with check (public.current_role() in ('administrator','planner'));
create policy "operational access" on public.routes for all to authenticated using (public.current_role() in ('administrator','planner') or expert_id in (select id from public.experts where user_id = auth.uid())) with check (public.current_role() in ('administrator','planner'));
create policy "operational access" on public.appointments for all to authenticated using (public.current_role() in ('administrator','planner') or expert_id in (select id from public.experts where user_id = auth.uid())) with check (public.current_role() in ('administrator','planner'));
create policy "operational access" on public.route_stops for all to authenticated using (exists (select 1 from public.routes r where r.id = route_id and (public.current_role() in ('administrator','planner') or r.expert_id in (select id from public.experts where user_id = auth.uid())))) with check (public.current_role() in ('administrator','planner'));
create policy "settings read" on public.settings for select to authenticated using (true);
create policy "admins manage settings" on public.settings for all to authenticated using (public.current_role() = 'administrator') with check (public.current_role() = 'administrator');
create policy "planners view imports" on public.import_history for select to authenticated using (public.current_role() in ('administrator','planner'));
create policy "planners create imports" on public.import_history for insert to authenticated with check (public.current_role() in ('administrator','planner'));
